### ISSUE TITLE
MRZ format

### ISSUE THREAD

**Issue by mahdi-salah** [alimertozdemir/EPassportNFCReader#10]
How can I read ( 3 lines MRZ ) instead of ( 2 lines MRZ ),

 Any help?

Thanks in advance.

![54290820-ee39cb80-45ab-11e9-8c5c-f6289fc530a7](https://user-images.githubusercontent.com/13225548/116887279-cea20900-ac32-11eb-8803-1652474a98b3.jpg)

**Comment by alimertozdemir** [comment]
Did you try to scan these passport and got an error? Could you please share error log then?

**Comment by mahdi-salah** [comment]
yes I tried to scan this passport and OCR cannot recognize it, and no error message display

**Comment by mahdi-salah** [comment]
yes, I tried to scan this passport but the OCR cannot recognize this MRZ.
