### ISSUE TITLE
Convert to Bitmap

### ISSUE THREAD

**Issue by LazyMink** [alimertozdemir/EPassportNFCReader#5]
Hello,
I would like to save the frame the mrz has been taken from.
I've tried to convert the ByteBuffer to a bitmap, but that fails. 

Is there a good way to save the frame as a bitmap?

I would really appreciate the help.
Thanks in advance.

**Comment by alimertozdemir** [comment]
Hi @Cressed
I am not sure google MLKit returns scanned text as bitmap or it is convertible to bitmap. 
I will control it asap if it is possible.

**Comment by LazyMink** [comment]
Hello @alimertozdemir 
Thanks for the reply.
The purpose for this is that I basically need a picture of the ID card or passport.

Thanks for any help you can provide.
I really appreciate it
