### ISSUE TITLE
Blocking Passport nfc chip. 

### ISSUE THREAD

**Issue by JackHack95** [alimertozdemir/EPassportNFCReader#8]
We are using this method for commercial purpose:
-is it possible to use it for free?
-doesn't this method block the NFC chip of the passport?
-And any important notes to avoid blocking the chip while testing?

We hope to hear from you soon.

**Comment by alimertozdemir** [comment]
- Yes it is for free. 
- No, I just reading data from chip, however if you change code on purpose it may block your chip card. There is no guarantee of "your" additional code implementation on this project.
- Same as above

**Comment by JackHack95** [comment]
Ok thank you for response
